### PR TITLE
Create copenhagen.md

### PR DESCRIPTION
**Pull request by hellvix**
Created a page with Copenhagen's city general information.

### CODE REVIEW

**Comment by benjaoming** [comment]
This looks like a nice text! But shouldn't you get hugo running locally? It's really easy to install and use and will make it possible to preview new pages locally :)

**Comment by hellvix** [comment]
> This looks like a nice text! But shouldn't you get hugo running locally? It's really easy to install and use and will make it possible to preview new pages locally :)

Not really. I have been editting these pages in different machines. I don't want to have to install hugo in all of them. xD
It's just more practical to use GitHub.

**Comment by benjaoming** [comment]
aaaaaand.. deployed! :tada: 

https://2019.djangocon.eu/copenhagen/

**Comment by hellvix** [comment]
> aaaaaand.. deployed! 
> 
> https://2019.djangocon.eu/copenhagen/

Nice! However it is not under the main menu.

**Comment by benjaoming** [comment]
@hellvix 
image

**Comment by hellvix** [comment]
> @hellvix
> image

LOL. I'm blind. Thanks.

**Pull request merged**
