### PR TITLE
Sitemap

### PR DESCRIPTION
**Pull request by lorinkoz**
- Added explicit sitemap config with all pages with equal priority and weekly change frequency. These can be changed on a per-page basis, in the page frontmatter, like:
```
sitemap:
  changefreq: "monthly"
```
- Added `link rel=...` to header.
- Added sitemap link to footer (also enhanced the current data in footer for beter integration with additional links, subject to designer's approval)

### CODE REVIEW

**Comment by benjaoming** [comment]
But this PR is very nice :) I like it, too, helps the search engines, right?

**Comment by lorinkoz** [comment]
Yes, but I am now working in the true meat of what you wanted, in addition to this.

-----Mensaje original-----
De: "Benjamin Bach" <notifications@github.com>
Enviado el: ‎27/‎01/‎2019 14:03
Para: "djangocon/2019.djangocon.eu" <2019.djangocon.eu@noreply.github.com>
CC: "Lorenzo Peña" <lorinkoz@gmail.com>; "Author" <author@noreply.github.com>
Asunto: Re: [djangocon/2019.djangocon.eu] Sitemap (#116)

But this PR is very nice :) I like it, too, helps the search engines, right?

**Comment by benjaoming** [comment]
Nice! Thanks! I like it a lot :)

Can the font become larger? 0.9rem looks better?

Do you know a fix for the mobile view?

image

**Comment by lorinkoz** [comment]
@benjaoming Oops, sorry for the bug. Please check again.

**Comment by lorinkoz** [comment]
Using `.85rem`. At `.9rem` it starts wrapping text in my 13 incher.

**Pull request merged**
